# -*- coding: utf-8 -*-
"""Create API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136nojuPIfXSJBY-SWE6ZHwYqKMisTSoV
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

import sklearn
import joblib

candidates=pd.read_csv('/content/candidate_job_role_dataset.csv')
jobs=pd.read_csv('/content/naukri_data_science_jobs_india.csv')

candidates.head()
jobs.head()

pip install fastapi uvicorn joblib pandas scikit-learn nltk

import joblib

model = joblib.load("job_candidate_matcher.pkl")

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import re
import nltk
from nltk.corpus import stopwords


nltk.download('stopwords')
STOP_WORDS = set(stopwords.words("english"))


def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z ]', ' ', text)
    words = [w for w in text.split() if w not in STOP_WORDS]
    return " ".join(words)


model = joblib.load("job_candidate_matcher.pkl")

# FastAPI app

app = FastAPI(title="Job–Candidate Matching API")


class Candidate(BaseModel):
    skills: str
    qualification: str
    experience_level: str
    job_role: str

class Job(BaseModel):
    Job_Role: str
    Skills_Description: str


def explain_match(candidate, job, top_n=5):
    cand_words = set(clean_text(candidate.skills).split())
    job_words = set(clean_text(job.Skills_Description).split())
    return list(cand_words.intersection(job_words))[:top_n]


@app.post("/predict")
def predict(candidate: Candidate, job: Job):
    text = clean_text(
        candidate.skills + " " +
        candidate.qualification + " " +
        candidate.experience_level + " " +
        candidate.job_role + " " +
        job.Job_Role + " " +
        job.Skills_Description
    )
    prob = model.predict_proba([text])[0][1]
    keys = explain_match(candidate, job)
    return {"fit_score": round(prob*100, 2), "key_matching_factors": keys}

!uvicorn app:app --reload --host 0.0.0.0 --port 8000

!ngrok authtoken 37RZRbuqgAMeWliemzF7KMf2Mab_uJ4xZQyRDeZV1ectJAaT

from pyngrok import ngrok
import uvicorn
import threading


public_url = ngrok.connect(8000)
print("Public URL:", public_url)

# Start FastAPI server in a thread
def run():
    uvicorn.run("app:app", host="0.0.0.0", port=8000)

threading.Thread(target=run).start()